import  Timeline  from "./components/Timeline";
export default function Home() {
  return (
   <>
    <head>
      <title>SNS udemy</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width,initial-scale=1.0" />
      <link rel="icon" href='/favicon.ico' />
    </head>
    <div>
      <Timeline />
    </div>
   </>
  )
}
